FROM ubuntu:18.04
MAINTAINER KaiPark <>

RUN mkdir /app
WORKDIR /app

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y build-essential python
RUN apt-get install -y curl git-all

ENV NODE_VERSION 13
RUN curl -sL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash -
RUN apt-get install -y nodejs
RUN npm i -g npm

COPY . .

RUN npm i && npm install -g nodemon cross-env eslint npm-run-all node-gyp node-pre-gyp

## THE LIFE SAVER
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

#CMD /wait && nodemon bin/www
CMD nodemon bin/www
