version: '3.7'
services:
#  tripbtoz-mdb:
#    image: mariadb:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: tripbtoz
#    ports:
#      - "3308:3306"
#    volumes:
#      - ./data/mariadb:/var/lib/mysql
#  tripbtoz-mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123
#      MONGO_INITDB_DATABASE: tripbtoz
#    ports:
#      - "27019:27017"
#    volumes:
#      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
#      - ./data/mongo:/data/db
  tripbtoz-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    command: nodemon bin/www
    ports:
      - "8180:8080"
#    links:
#      - tripbtoz-mdb
#      - tripbtoz-mongo
#    depends_on:
#      - tripbtoz-mdb
#      - tripbtoz-mongo
#    environment:
#      WAIT_HOSTS: tripbtoz-mdb:3306, tripbtoz-mongo:27017
